CREATE DATABASE IF NOT EXISTS para_db;
USE para_db;

SET @encryption_key = UNHEX(SHA2('b5c2a8d4f9e7b1a6d2e3c7f8a9b4c6d5f0a1b2e3c4d5e6f7a8b9c0d1e2f3a4', 256));

CREATE TABLE IF NOT EXISTS users (
    id BINARY(16) PRIMARY KEY,
    full_name VARBINARY(255) NOT NULL,
    email VARBINARY(255) NOT NULL,
    avatar_url VARCHAR(512) NULL,
    password_hash VARCHAR(255) NOT NULL,
    is_locked TINYINT(1) NOT NULL DEFAULT 0,
    failed_login_attempts INT NOT NULL DEFAULT 0,
    locked_until DATETIME DEFAULT NULL,
    last_login_attempt DATETIME DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_email (email(255))
);

CREATE TABLE IF NOT EXISTS messages (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BINARY(16) NOT NULL,
  text TEXT NOT NULL,
  is_bot TINYINT(1) NOT NULL DEFAULT 0,
  timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  error TEXT DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX idx_user (user_id),
  CONSTRAINT fk_user
    FOREIGN KEY (user_id)
    REFERENCES users(id)
    ON DELETE CASCADE
);

DELIMITER //
CREATE FUNCTION IF NOT EXISTS decrypt_email(encrypted_email VARBINARY(255), key_bin BINARY(32))
RETURNS VARCHAR(255)
READS SQL DATA
DETERMINISTIC
BEGIN
    RETURN CAST(AES_DECRYPT(encrypted_email, key_bin) AS CHAR);
END//
DELIMITER ;

DELIMITER //
CREATE FUNCTION IF NOT EXISTS decrypt_full_name(encrypted_name VARBINARY(255), key_bin BINARY(32))
RETURNS VARCHAR(255)
READS SQL DATA
DETERMINISTIC
BEGIN
    RETURN CAST(AES_DECRYPT(encrypted_name, key_bin) AS CHAR);
END//
DELIMITER ;
